### ISSUE TITLE
Chrome/Brave Update has Disabled Ledger U2F Support

### ISSUE THREAD

**Issue by phinatic** [chainapsis/keplr-extension#102]
The latest chromium update has disabled u2f support, meaning Kepler, along with other wallets, can no longer connect to a Ledger device. MetaMask has worked around the issue by integrating with Ledger Live directly. See this notice from MetaMask.

<img width="490" alt="Screen Shot 2021-05-28 at 2 53 16 PM" src="https://user-images.githubusercontent.com/16869740/120049316-10ba3280-bfc6-11eb-8cf6-65f103e83eed.png">

**Comment by martinholovsky** [comment]
I can confirm, I'm unable to use Ledger anymore. The same applies to the latest Brave browser. This is quite serious and ignorant of Google guys.

**Comment by dogemos** [comment]
Hi @phinatic and @martinholovsky,

First of all thanks for the heads up! We're aware of the issue and have been able to confirm that Ledger hardware wallet support on Keplr is currently not working since the Chrome 91 update.

Note that Keplr currently supports both WebUSB / HID option to connect to the hardware wallets (default is WebUSB, HID used when 'Using Ledger Nano X on Windows?' checkbox is enabled). (ref https://github.com/chainapsis/keplr-extension/issues/25)

We've tested on Windows and Mac with both the Ledger Nano S / Nano X with the following results:
* Windows / WebUSB - Not working
* Windows / HID - Not working
* MacOS / WebUSB - Not working
* MacOS / HID - Working

Right now we're tracking [this](https://github.com/LedgerHQ/ledgerjs/issues/607) issue on the Ledger repository, and will aim to address the problem ASAP.

For now, and from my tests–it appears that checking this 'Using Ledger Nano X on Windows?' option on a Mac is the only working option. Please let me know if you have any additional data that could be helpful as well.

**Comment by toml01** [comment]
Was this resolved? Working for me right now on chrome version `91.0.4472.77`
