### ISSUE TITLE
Keplr offlineSigner failing with StargateSignClient

### ISSUE THREAD

**Issue by jackzampolin** [chainapsis/keplr-extension#142]
See details here:

https://github.com/cosmos/cosmjs/issues/872

We are looking for a full working example of using keplr and cosmjs to sign a transaction

**Comment by Thunnini** [comment]
Since keplr itself only provides signatures, if there is a problem, there is a high probability that it is on the cosmjs side. There still seems to be bugs in cosmjs for messages sent in proto encoding. What message were you trying to send? Or alternatively, just use the launchpad version of cosmjs. It will work because stargate supports amino for backward compatibility.
