### ISSUE TITLE
support IBC token transfers to the native blockchain

### ISSUE THREAD

**Issue by arno01** [chainapsis/keplr-extension#144]
Keplr says the Address is incorrect when I'm trying to use "Send" (not the IBC transfer).
I can only transfer them as IBC tokens between the blockchains using Keplr-extension, but not natively.

Example transaction made with Emeris (but can't be made with Keplr-extension as of now), sent DVPN tokens from Cosmos (ATOM) blockchain to the Sentinel (DVPN) [natively, not as the IBC token!]:

```
{
  "chain_id": "cosmoshub-4",
  "account_number": "349346",
  "sequence": "31",
  "fee": {
    "gas": "700000",
    "amount": [
      {
        "denom": "uatom",
        "amount": "28000"
      }
    ]
  },
  "msgs": [
    {
      "type": "cosmos-sdk/MsgTransfer",
      "value": {
        "source_port": "transfer",
        "source_channel": "channel-186",
        "token": {
          "amount": "4266312760",
          "denom": "ibc/42E47A5BA708EBE6E0C227006254F2784E209F4DBD3C6BB77EDC4B29EF875E8E"
        },
        "sender": "cosmos17s6ucafgwc9khrvgphemalcuxz2lv2uc9tdm7y",
        "receiver": "sent17s6ucafgwc9khrvgphemalcuxz2lv2uc7smz6t",
        "timeout_height": {},
        "timeout_timestamp": "1630400318739000000"
      }
    }
  ],
  "memo": ""
}
```

Sent https://atom.tokenview.com/en/tx/B12A7DF6C25D544FD81FF26448FB6BAE88986B5CD0F3CBA79B0BDD2A9CFCCCAE
Arrived https://explorer.sentinel.co/transactions/33817AFF2A272994775B125D4B26549885DF6BFEBA9B62376D9275CEAD073836

That's Emeris's "Send" -> "Send to address" (not the "Move assets").

**Comment by dogemos** [comment]
Hey there, and apologies for the late response here.

Due to the non-fungibility of IBC transfers due to the notion of 'channels', the Keplr team has decided that the IBC transfers within extension wallet should mostly be used by advanced users who understand IBC nuances well.

We suggest a UX flow where the web-app suggests the channel for the user, rather than the user having to figure this out and filling it in in the wallet as mistakes can lead to temporary freezing funds (if there are no relayers).
