### ISSUE TITLE
Torus sign in with Google

### ISSUE THREAD

**Issue by fadeev** [chainapsis/keplr-extension#27]
Would love to try out Keplr's sign in with Google, but unfortunately Keplr extension asks me to enter my Google credentials into an anonymous window. This window has no URL bar and I can't verify that I'm in fact sending my credentials to https://accounts.google.com and not some random phishing website.

<img width="1396" alt="Screenshot 2020-08-31 at 16 16 22" src="https://user-images.githubusercontent.com/332151/91714504-59fb6400-eba5-11ea-803f-08560238465a.png">

**Comment by Thunnini** [comment]
Thank you for bringing this up.

Currently, Keplr uses the `chrome.identity.launchWebAuthFlow` API to authenticate the sign in and gets the token from Google.

However, in the extension environment, we aren't able to get the token the same way webpages requests authentication, which redirects to the webpage with the token after sign-in. Chrome extension's URL starts with chrome-extension://, but such URL is prevented by Google. 

We could explore another way that hosts the own webpage and gets the token from this webpage indirectly...
The design decision to use `chrome.identity.launchWebAuthFlow` was because this allows the extension to work without dependencies on external websites, which would allow other projects to fork Keplr for their project more easily.

**Comment by fadeev** [comment]
Thanks, makes sense!
