### ISSUE TITLE
Stargate readiness?

### ISSUE THREAD

**Issue by zmanian** [chainapsis/keplr-extension#33]
The Stargate upgrade is nearly feature complete and the Stargate team is working with wallet teams to ensure they are ready for stargate.

We are currently running the stargate-3 testnet to enable wallets to test their integrations against stargate.

We expect the stargate software to be in feature freeze shortly.

We would also strongly encourage wallets to test their integrations against the legacy rest amino interface and to experiment with the new GRPC interfaces.

**Comment by Thunnini** [comment]
At this time the plan is to test support through legacy amino by rest api in the next week or two. We’re still unclear on the timeline for gRPC.

**Comment by faboweb** [comment]
As Keplr uses the cosmjs launchpad version it is not yet compatible to stargate

**Comment by zmanian** [comment]
https://twitter.com/simon_warta/status/1327684536482885633?s=20

Leads me to believe that it should be trivial for cosmjs users to upgrade to stargate.

**Comment by faboweb** [comment]
But is @cosmjs/stargate backwards compatible? If though, let's switch over right away

**Comment by faboweb** [comment]
@webmaster128 would it be possible to migrate already to the stargate version or would that break compatibility with launchpad networks and older?

**Comment by webmaster128** [comment]
We develop a stargate client in @cosmjs/stargate, which [is now compatible to rc3](https://github.com/cosmos/cosmjs/tree/master/packages/stargate#supported-cosmos-sdk-versions). If you use @cosmjs/launchpad today, and are familiar with the CosmJS tooling, the upgrade should relatively easy.

However, Keplr is not based on CosmJS as far as I know, making Step 1 from my tweet above a good chunk of work. I don't know if the Keplr team wants to go that route.

Design decisions we do at CosmJS regarding Stargate:
- Give up connecting to the LCD API because API stability is a vague promise that is hard to guarantee, especially since there are no API specs, documentation and tests; Instead all communication goes through Tendermint RPC. This allows us to verify light client proofs.
- Give up Amino JSON legazy signing. We implemented SIGN_MODE_DIRECT.

So we want to go all in with the Stargate support, have a separate Launchpad package and avoid wasting time debugging bugs in compatibilty layers.

Known limitations (i.e. things that worked in Launchpad and do not exist in stargate yet):
- Search by sender/recipeint/tags: https://github.com/cosmos/cosmjs/issues/532 https://github.com/cosmos/cosmjs/issues/533
- Wallets (`DirectSecp256k1HdWallet`) cannot be serialized for encrypted key storage
- Different account types: https://github.com/cosmos/cosmjs/issues/354
- Log parsing: https://github.com/cosmos/cosmjs/issues/376
- CosmWasm support: https://github.com/cosmos/cosmjs/issues/491

None of those should be a big deal. It just has to be done. Feel free to name your priorities.

> But is @cosmjs/stargate backwards compatible? If though, let's switch over right away

Nope, @cosmjs/stargate supports SDK 0.40.0-rc3 and @cosmjs/launchpad supports SDK 0.37–0.39.

**Comment by faboweb** [comment]
So Keplr would need to allow specification of the version of a network so it can switch between using stargate or launchpad libraries.

> However, Keplr is not based on CosmJS as far as I know

Keplr uses CosmJS for querying and signing

**Comment by webmaster128** [comment]
> As Keplr uses the cosmjs launchpad version

I think this is a major misconception. The only place where Keplr uses CosmJS is in a script injected into web pages, allowing apps built with CosmJS to interact with Keplr.

```
$ git grep '@cosmjs/' src
src/content-scripts/inject/cosmjs-offline-signer.ts:} from "@cosmjs/launchpad";
src/content-scripts/inject/cosmjs-offline-signer.ts:import { toHex, fromHex } from "@cosmjs/encoding";
```

The extension itself (key storage, querying, signing, broadcasting …) as well as Chainapsis' wallet is based on [cosmosjs](https://github.com/chainapsis/cosmosjs), a library developed by Chainapsis.

**Comment by Thunnini** [comment]
@webmaster128 is correct.

At this time, web front-ends can request signing using CosmJS, but we used CosmosJS internally for Keplr Extension. As for Stargate, we have built an experimental version during HackAtom which Keplr was able to support Stargate blockchains, and most of the key functionalities worked without issue (Cosmos-SDK v0.40.0-rc0). However, as IBC transfer messages do not use the hybrid codec, we weren’t able to support IBC transfers via the REST API.
We’re starting to notice that Keplr codebase has gotten a lot more complicated recently, and are working on refactoring most of the codebase. We are considering using CosmJS instead of CosmosJS for the extension internally, but this hasn’t been decided yet.

**Comment by faboweb** [comment]
What is the strategy in the meantime? Currently, we can't use a combination of @cosmjs/stargate and Keplr. Keplr injects a signer based on @cosmjs/launchpad which doesn't have `signAmino` functionality. Can we inject 2 versions of the offline signer, one for stargate and one for launchpad allowing at least the client to choose between both?

**Comment by faboweb** [comment]
Ok, my approach so far is to just not use the `SigningCosmosClient` and handle querying and broadcasting manually.

**Comment by emperorjm** [comment]
Is there any update on the stargate implementation of Keplr? I am no longer using Amino so all my endpoints are gRPC, so I wanted to know if I can utilize Keplr or would I need to find another solution.

**Comment by dogemos** [comment]
Hi @emperorjm, we're in the process of refactoring the Keplr extension code in the [refactor branch](https://github.com/chainapsis/keplr-extension/tree/refactor), and gRPC support will come after the completion of the refactor.
In terms of timeline, please note that we are planning on launching initial Stargate Keplr with legacy Amino REST endpoints only. Support for gRPC will come later through the gRPC HTTP gateway–so REST will still be used.

**Comment by emperorjm** [comment]
Hi @dogemos . I am able to execute RPC based transactions using **"SigningStargateClient"** within the **"@cosmjs/stargate"** package. The stargate branch within the Keplr Example repo (https://github.com/chainapsis/keplr-example/tree/stargate) provides some boilerplate code.

**Comment by dogemos** [comment]
Closing as `cosmoshub-3` has now successfully migrated to `cosmoshub-4` with Keplr support.
