### ISSUE TITLE
Secret-wasm implementation

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-extension#36]
## Introduction

An early experimental implementation that only approves the access for testnet(holodeck) was implemented in chainapsis/keplr-extension@eb82a5a

And the initial example is here even though it is written very straightforward and hard to read yet: https://github.com/chainapsis/keplr-example/blob/secret-wasm/src/main.js

### Deterministic creation of transaction encryption key for each account

While Keplr could randomly generate a transaction encryption key and store it locally rather than creating it deterministically, this leads to another issue where the user loses access to their encryption key when Keplr is deleted from the browser. An alternate way to prevent this could be to reveal the encryption key to the user and allow them to store it. However, this leads to user experience issues where a user may choose to not safely store their encryption keys due to inconvenience.

Therefore, the mechanism we propose is to deterministically derive the encryption key within Keplr.

A webpage can request encryption/decryption of user information by requesting it to Keplr. The reason for is that when a webpage handles the encryption/decryption, Keplr will not be able to decrypt the message for user to verify and sign. An alternate way would be for the website/Keplr to send the encryption key to Keplr to each other, but this may lead to potential security vulnerabilities to exist.

### Considerations

* Should Keplr notify the user when we receive a request to encrypt in a similar fashion as approving/rejecting transactions?
* Should msg decryption have the same approval process as the encryption process(similar to what is proposed above)?

### Encryption/Decryption Logic

The logic of how Keplr encrypts/decrypts secret-wasm msgs can be examined [here](https://github.com/chainapsis/keplr-extension/blob/secret-wasm/src/background/secret-wasm/keeper.ts#L15)

In the code above, Keplr creates the tx encryption using the seed of the currently selected key, receiving the signature of `secret-seed-for-${chainId}` and hashing the signature. However, this creates additional complications when considering extensibility to Ledger hardware wallets. The Ledger Cosmos app signs json formatted text, and check to ensure that it follows stdTx of Cosmos-SDK. Therefore, in order for Ledger signing to work the text to be signed must be in the following format:
```javascript
JSON.stringify({
  // eslint-disable-next-line @typescript-eslint/camelcase
  account_number: 0,
  // eslint-disable-next-line @typescript-eslint/camelcase
  chain_id: chainId,
  fee: [],
  memo: "secret-seed",
  msgs: [],
  sequence: 0
})
```
While the format above can be tricky to work with (assuming this will work with the Ledger), it should allow receiving of the signature back from the Ledger. Keplr will use the method of using the returned signature's hash as seed for the tx encryption key.

In this type of implementation, the webpage must not utilize enigma utils that's included in secretjs but rather the enigma utils injected by Keplr. Currently Keplr's enigma utils implementation looks like [this](https://github.com/chainapsis/keplr-extension/blob/secret-wasm/src/content-scripts/inject/enigma-utils.ts) and allows for background communication to receive encryption/decryption results from Keplr.

The [following line of code in the example](https://github.com/chainapsis/keplr-example/blob/secret-wasm/src/main.js#L109) forcefully injects Keplr's enigma utils into secretjs. As the secretjs implementation only allows the usage of enigma utils within secretjs, this ignores the definition to utilize Keplr's enigma utils. In the following mechanism, the webpage is able to show the msg of `MsgExecuteContract`back to the user after the user approves decryption. However, it must be noted that as Ledger's Cosmos app doesn't have the encrypt/decrypt functionalities unique to Secret Network, users will not be able to verify the transaction message on the Ledger and must trust Keplr.

We'd like to request feedback to verify that creating a tx encryption key as proposed above is secure. Also, we'd like to request that secretjs be modified to allow custom enigma utils.

Finally, we'd like to discuss how to best approach the issues that exist with using the Ledger Cosmos app to sign secret-wasm transactions.

**Comment by Cashmaney** [comment]
Sorry for the delayed response.

Thanks for raising these issues. We can definitely modify secretjs to allow custom enigmautils. If we're doing that, though, do you think it would be cleaner to be able to overload the specific functions, rather than the entire enigmautils? (i.e, instead of injecting _enigmautils_, you could inject your own _encrypt_ and _decrypt_ ). While that might take a tiny bit more work on our end to clean things up, it would perhaps result in clearer code and an interface that is easier to use.

Re: the tx encryption/decryption key - I think the default mode should be that Keplr handles encryption/decryption, since that also makes life a little easier for the website. Also, encryption/decryption (without signing) should probably not require user interaction, since I don't feel like a user would care enough to justify the extra friction of manual authentication. 

In terms of how to generate a deterministic key - not exactly sure what functions you can use, but in general the conventional way (I'm aware of) of doing something like this would be SHA3(k||m), though I know that when using something like ledger that sort of construct probably isn't available. I think your way of doing it is probably fine, as long as it is acceptable that:

* Theoretically the user is open to an attack where a malicious site could try and get them to sign the data used to generate the deterministic key 
* When using something like ledger it wouldn't require two inputs to sign a message. 

I think it would be simpler to start with a random key stored locally, as you suggested originally (and allow a user to export it in the form of some mnemonic if he wants to). The reason this is probably acceptable is that the encryption key is only used for transient transactions, and in most cases either: 

1. The underlying application will be storing long-term user related data as it comes in
2. The secret contract will have some historical query (e.g. secret-20 has a query history function)
3. The transaction data is not important for long-term storage

These are just my current assumptions which could be wrong of course:)

Thanks for all the great work!

**Comment by assafmo** [comment]
I agree with @Cashmaney.

Also, I don't think you need to inject your own `EnigmaUtils` to the webpage, you can inject a pre-initialized `SigningCosmWasmClient`. See [this](https://github.com/enigmampc/SecretHoldEm/blob/c0db2973a36c8790247e9fe59c0bbdfaa498be7d/gui/src/App.js#L86-L116) usage example.

You can generate the `seed` however you want as long as it's a 32-byte `Uint8Array` and a secret. [This](https://github.com/enigmampc/SecretNetwork/blob/741217a931596a37a595d5c4adc8b5f68ec82be7/cosmwasm-js/packages/sdk/src/enigmautils.ts#L68-L70) is how we're doing it, but I'd suggest you derive it deterministically from the user's mnemonics or private wallet key. This way the user only needs to back up the mnemonics which they're already doing.

As for ledger, we need to find someway to generate a deterministic secret using the ledger... Or just use a password maybe? It's worse UX though. Need to think about it more.

**Comment by Thunnini** [comment]
@assafmo Sorry for the late response.

Personally, I would prefer not to inject the `SigningCosmWasmClient` itself as it can limit the usage of specific `SigningCosmWasmClient` that Keplr injects. I am worried that if we limit ourselves to this flow, we may have some compatibility issues on front-ends with more legacy version of `SecretJS` once Keplr updates to a newer version of SecretJS that gets injected.

If the interface of `EnigmaUtils` is determined and it doesn't need to update frequently, and it is maintained across multiple versions, the developers can choose the version of `SecretJS` they want, and they just need to use the Keplr's `EnigmaUtils` when they use `SecretJS`.

Also, as I may change how tx encryption keys are derived further down the road, but for now will be using the method of deriving the encryption key from the use’s signature as suggested above. Creation of random tx encryption key, import, and export features can be added later.

**Comment by assafmo** [comment]
`EnigmaUtils` isn't going to change a lot.

**Comment by Cashmaney** [comment]
Apologies for the delay. @Thunnini Would this resolve the issue?

https://github.com/enigmampc/SecretNetwork/pull/607/files

**Comment by assafmo** [comment]
secretjs@0.9.20 on NPM now has the `SecretUtils` interface.
Your feedback is most welcome. 😇
