### ISSUE TITLE
Support for coralnet/heldernet

### ISSUE THREAD

**Issue by abefernan** [chainapsis/keplr-extension#37]
I'm trying to add Keplr support to [CosmWasm's CosmJS dApps](https://github.com/CosmWasm/dApps) and with the latest version of Keplr (0.6.7) I am not able to see Coralnet as a chain option, so I cannot test the dApps.

**Comment by Thunnini** [comment]
Currently, Keplr supports the feature that adds the chain from the webpage experimentally. Check this page: https://wallet.keplr.app/#/cosmwasm-coral/cw20 and this code: https://github.com/chainapsis/keplr-example/blob/master/src/main.js#L19

I'm not sure that Keplr can support Heldernet well because I haven't tested it yet. However, if Heldernet and Coralnet are almost similar, it can work well by the above way.

**Comment by abefernan** [comment]
Thank you! I'll try it out

**Comment by abefernan** [comment]
Closing since Keplr support has been successfully added to [dApps](https://github.com/CosmWasm/dApps/pull/50)
