### ISSUE TITLE
Cosmos Staking

### ISSUE THREAD

**Issue by mmmoussighi** [chainapsis/keplr-extension#46]
Hi!  I am a newbie, and I just transferred a small amount of ATOM to Keplr for staking.  I have tried to stake my balance 3 separate times, each time being charged for "gas," but my balance still shows in my "Available" rather than "Staked." See below:

![image](https://user-images.githubusercontent.com/74617436/100785226-f831dc80-33d5-11eb-9cef-7961ff735eb1.png)

Do you have any suggestions as to why this might be happening, and how to correct it?  Thanks!

**Comment by dogemos** [comment]
Hi @mmmoussighi,

This is likely due to you attempting to stake the all of the available amount, and not accounting for fees. The transaction will fail (and fees will not be refuneded) as your staking requested amount + fee is smaller than the total available amount. Please make sure you only stake the total available amount minus about 0.1 ATOM in case you need to claim rewards later.

**Comment by mmmoussighi** [comment]
Oh dear.  That would have been nice to know.  Thank you for clearing that up for me!

**Comment by mmmoussighi** [comment]
One more question about staking.  Is it preferable to have the voting power and commission higher or lower?

![image](https://user-images.githubusercontent.com/74617436/100791249-95910e80-33de-11eb-9396-b91c16b48aab.png)

**Comment by dogemos** [comment]
Voting power = the % share of total staked amount that the validator has
Commission = how much % of your staking reward the validator gets for their service

Personally, I recommend aiming for a reputable 30-60 validators with reasonable commission to help spread out the voting power.
