### ISSUE TITLE
Unable to send STR using the dapps interface

### ISSUE THREAD

**Issue by raykyri** [chainapsis/keplr-extension#47]
I have no problems sending STR from within Keplr, but sending STR or conducting any sort of transaction using CosmJS and the extension causes Keplr to return an error on the background page (see https://github.com/hicommonwealth/keplr-example):

```
generated_background_page.html

reject-tx-builder-config occurs error: Unknown request id
background.bundle.js:59 request-sign occurs error: Request rejected
```

Where does the "reject-tx-builder-config" message come from? Github Search doesn't point to what throws it. Is it coming from a private module?

**Comment by Thunnini** [comment]
"reject-tx-builder-config" error comes from the background process of the extension. The keyring keeper on the background process handles the requested tx config and signing, which is not private.

Even though I wasn't able to reproduce your error, I found some mistakes in the code.

First, while STR is the value displayed for the user, `astr`(atto STR) is actual denomination used by the chain to do calculations. So, you should send not `str` but `astr`.
https://github.com/hicommonwealth/keplr-example/blob/master/src/main.js#L170

And because `astr`'s decimal is 18, you should multiply the STR value by 10**18. Keplr's example uses ATOM (which has 6 decimal points / 10**6), so please keep this in mind when you are referring to the example.
https://github.com/hicommonwealth/keplr-example/blob/master/src/main.js#L151

**Comment by raykyri** [comment]
That was the issue! Tracing through the deminified Chrome extension (popup.html) revealed the same thing, an invalid currency. You guys were definitely faster to diagnose it.
