### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-extension#56]
Hello,
   Please make a firefox extension as metamask has too! (it's easy since both firefox and chrome use the same technologies)
   
Thank you

**Comment by dogemos** [comment]
Hi @chmichael, as per discussions [here](https://github.com/chainapsis/keplr-extension/issues/50), we are not planning on adding Firefox support in the immediate future due to reoccurring issues with cross-browser compatibility that we simply don't have ample resources to manage at this time.

We will keep this in mind, and reconsider this as the team expands and we have more resources.

Thank you for your suggestions, and please feel free to let me know if you have any other suggestions!
