### ISSUE TITLE
Internal server error when signing transactions

### ISSUE THREAD

**Issue by cmwaters** [chainapsis/keplr-extension#61]
This is probably not going to be too helpful of a description, but in the last two occasions where I tried to sign a transaction, one for a withdrawal and another for a redelegation, I received a `500 error`. However, upon waiting a bit longer, I noticed that the transaction eventually went through. Not too sure if this is a problem or not

**Comment by dogemos** [comment]
Hi @cmwaters,

Our Cosmos Hub endpoints have been a bit unstable after the Stargate upgrade due to issues regarding nodes falling out of sync under high query loads (https://github.com/tendermint/tendermint/issues/6122). We've been working with our node providers to alleviate the issue, but it seems that the issue shows up when there's a lot of concurrent requests.

That being said, we'll see if we can improve the error message to better communicate that the transaction has been broadcasted, but Keplr has timed out waiting for the verification of the transaction and for the user to check the explorers before making a new transaction.

Cheers!

**Comment by dogemos** [comment]
Hi @cmwaters,

Keplr v0.8.4 that has been released will resolve this issue.

Keplr now only claims rewards from the highest 8 pending reward validators. If you want to claim rewards from the remaining validators, you'll have to click on the 'claim reward' transaction twice.
