### ISSUE TITLE
No easy way of exporting/importing Secret Network viewing keys with their associated contract address

### ISSUE THREAD

**Issue by nejinx** [chainapsis/keplr-extension#82]
Add the ability to export all viewing keys /contract address at once to avoid the need to create new ones on extension/remove/reinstall or to use this extension on multiple browsers. It is quite time consuming to do this manually. Just to clarify, this is in conjunction with the contract address as viewing keys themselves can be copied.

This would be a great quality of life update.

If this isn't the appropriate location for feature requests I am happy to put elsewhere.

**Comment by dogemos** [comment]
Hi there,

Finally working through some old issues and doing some end of the year repo-housekeeping!

At this time, I think non-signing related network specific features should be handled by the webapp. Since Keplr v0.9.5, we've allowed frontends to suggest/get Secret viewing keys to/from Keplr, instead of being handled by the extension itself.

While currently there is the pain of having to approve multiple popups if you have lots of tokens, this can be addressed in the future with Keplr allowing adding of multiple tokens in the same popups.
