### ISSUE TITLE
Error message when going back after changing fee for claim staking reward

### ISSUE THREAD

**Issue by dogemos** [chainapsis/keplr-extension#9]
**Bug description**
`Fail to withdraw rewards: Request rejected` popup shows up after going back from claiming staking rewards and changing the tx fee.

**Steps to reproduce**
1. Click 'Claim' button for pending staking reward
2. Change fee to low or high
3. Hit back
4. Wait a few minutes
5. `Fail to withdraw rewards: Request rejected` shows up

**Comment by Thunnini** [comment]
I think that this occurs because the keyring background that manages the user's account and signing request deals with the request as a failure(request rejected) if no action is delivered for 3 minutes.
When users request claiming pending rewards in the extension's frontend, it requests the fee-setting and redirects to the fee-setting page. But, in this case, the fee-setting request remains even though users canceled the fee-setting. So, after 3 minutes, it throws the "request rejected" error.
I will fix this bug by making it ignored after users cancel the fee-setting.

**Comment by Thunnini** [comment]
And, I found that the same problem occurs when a user sends assets and cancels on the signing page.
Claiming rewards request skips the signing approval, and sending assets skips the fee-setting. So, if you press the back button on the signing page when you send some assets, it will throw the same error after 3 minutes.
